#!/bin/bash

# ====================================================
#  Cove Release Test Matrix
#  Description: Drives the Incus distro containers on the test box through
#               the pre-release checklist and renders a distro × check table.
#
#  Usage:
#    ./test-matrix.sh              # compile, deploy, run, wait, report
#    ./test-matrix.sh --async     # compile, deploy, launch, return immediately
#    ./test-matrix.sh report      # render the table for the current/last run
#    ./test-matrix.sh --no-compile ...   # skip ./compile.sh (use cove.sh as-is)
#
#  The box (override with COVE_TEST_BOX) hosts six Incus containers, each with
#  a "baseline" snapshot (clean OS + curl). Lanes:
#    A (all six):      fresh --dev install → add/clone/rename/login/delete →
#                      status/health/mailpit → container reboot survival
#    B (one apt/dnf):  previous GitHub release → candidate + post-upgrade
#    C (one apt/dnf):  install + add as a non-root sudo user
# ====================================================

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# The test box is deliberately not committed — set COVE_TEST_BOX in the
# environment, or put the SSH target (e.g. root@testbox.example.com) in an
# untracked .test-box file next to this script.
BOX="${COVE_TEST_BOX:-}"
if [ -z "$BOX" ] && [ -f "$SCRIPT_DIR/.test-box" ]; then
    BOX="$(head -1 "$SCRIPT_DIR/.test-box")"
fi
if [ -z "$BOX" ]; then
    echo "❌ No test box configured. Set COVE_TEST_BOX or create $SCRIPT_DIR/.test-box"
    exit 1
fi
REMOTE_DIR="/root/cove-tests"

COMPILE=true
ASYNC=false
ACTION="run"
for arg in "$@"; do
    case "$arg" in
        --no-compile) COMPILE=false ;;
        --async)      ASYNC=true ;;
        report)       ACTION="report" ;;
        up)           ACTION="up" ;;
        down)         ACTION="down" ;;
    esac
done

# up/down: manual fleet control. A run spins containers up automatically
# (the restore step starts them); a fully green run parks them again. These
# exist for poking at containers outside a run, and for parking after
# debugging a failure.
if [ "$ACTION" = "up" ]; then
    ssh "$BOX" "incus start \$(incus list -c n -f csv | grep '^cove-') 2>/dev/null; incus list -c ns -f compact"
    exit 0
elif [ "$ACTION" = "down" ]; then
    ssh "$BOX" "incus stop -f \$(incus list -c n -f csv | grep '^cove-') 2>/dev/null; incus list -c ns -f compact"
    exit 0
fi

render_report() {
    local raw
    raw=$(ssh "$BOX" "cat $REMOTE_DIR/matrix/results.txt 2>/dev/null; [ -f $REMOTE_DIR/matrix/DONE ] && echo '__DONE__'; [ -f $REMOTE_DIR/matrix/PARKED ] && echo '__PARKED__'")
    if [ -z "$raw" ]; then
        echo "No matrix results found on $BOX — has a run been started?"
        exit 2
    fi
    local done_flag=false
    grep -q '__DONE__' <<<"$raw" && done_flag=true

    echo "$raw" | grep '^CHECK|' | awk -F'|' '
    {
        c=$2; sub(/^cove-/, "", c)
        checks[$3]; conts[c]; v[$3,c]=$4
        if (!($3 in ord)) ord[$3]=++n
    }
    END {
        nc=0; for (co in conts) cols[++nc]=co
        # stable column order
        split("ubuntu2404 ubuntu2204 debian12 debian13 fedora43 rocky9", want, " ")
        printf "%-18s", "check"
        for (i=1;i<=6;i++) if (want[i] in conts) printf "%-12s", want[i]
        print ""
        for (k=1;k<=n;k++) {
            for (ch in ord) if (ord[ch]==k) name=ch
            printf "%-18s", name
            for (i=1;i<=6;i++) {
                if (!(want[i] in conts)) continue
                r=v[name,want[i]]
                s=(r=="PASS") ? "✓" : (r=="FAIL") ? "✗ FAIL" : (r=="SKIP") ? "–" : "…"
                printf "%-12s", s
            }
            print ""
        }
    }'

    local fails
    fails=$(grep -c '|FAIL$' <<<"$raw" || true)
    echo ""
    if ! $done_flag; then
        echo "⏳ Run still in progress ('…' = no result yet). Logs: $BOX:$REMOTE_DIR/matrix/*.log"
        exit 2
    elif [ "$fails" -gt 0 ]; then
        echo "❌ $fails check(s) failed. Containers left RUNNING for inspection —"
        echo "   logs: $BOX:$REMOTE_DIR/matrix/*.log · park when done: ./test-matrix.sh down"
        exit 1
    else
        if grep -q '__PARKED__' <<<"$raw"; then
            echo "✅ All checks passed. Fleet parked (containers stopped)."
        else
            echo "✅ All checks passed."
        fi
        exit 0
    fi
}

if [ "$ACTION" = "report" ]; then
    render_report
fi

# --- Build ---
if $COMPILE; then
    ( cd "$SCRIPT_DIR" && ./compile.sh >/dev/null )
fi
bash -n "$SCRIPT_DIR/cove.sh" || { echo "❌ cove.sh failed syntax check"; exit 1; }

# --- The box-side runner ---
RUNNER=$(mktemp)
cat > "$RUNNER" <<'RUNNER_EOF'
#!/bin/bash
# Box-side matrix runner (generated by test-matrix.sh — do not edit on the box).
D=/root/cove-tests/matrix
SRC=/root/cove-tests
rm -rf "$D"; mkdir -p "$D"

CONTAINERS="cove-ubuntu2404 cove-ubuntu2204 cove-debian12 cove-debian13 cove-fedora43 cove-rocky9"
UPGRADE_LANE="cove-ubuntu2404 cove-rocky9"
SUDO_LANE="cove-debian12 cove-fedora43"

res() { echo "CHECK|$1|$2|$3" >> "$D/results.txt"; }

restore() {
    local c=$1
    incus stop -f "$c" 2>/dev/null
    incus snapshot restore "$c" baseline
    incus start "$c"
    sleep 10
}

cx() { local c=$1; shift; timeout 600 incus exec "$c" -- "$@"; }

# Site checks retry a few times — a curl fired immediately after a Caddy
# reload (add/clone/rename all trigger one) can race the reload and see a
# transient failure that isn't a product bug.
http_code() { # container host -> http status of https://host.localhost/
    local code i
    for i in 1 2 3 4; do
        code=$(incus exec "$1" -- curl -sk -o /dev/null -w '%{http_code}' --max-time 20 "https://$2.localhost/")
        [ "$code" = "200" ] && break
        sleep 3
    done
    echo "$code"
}

site_has() { # container host needle
    local i
    for i in 1 2 3 4; do
        if incus exec "$1" -- curl -sk --max-time 20 "https://$2.localhost/" | grep -q "$3"; then
            return 0
        fi
        sleep 3
    done
    return 1
}

lane_a() {
    local c=$1 L="$D/$c.log"
    {
        restore "$c"
        incus file push "$SRC/cove.sh" "$c/root/cove.sh"
        incus file push "$SRC/install-cove.sh" "$c/root/install-cove.sh"

        if cx "$c" bash /root/install-cove.sh --dev && cx "$c" cove version | grep -q "Cove version"; then
            res "$c" install PASS
        else
            res "$c" install FAIL
            for k in add_latest add_pinned add_plain clone rename login delete status health mailpit reboot; do res "$c" "$k" SKIP; done
            return
        fi

        if cx "$c" cove add alpha && site_has "$c" alpha "Welcome to alpha"; then
            res "$c" add_latest PASS
        else
            res "$c" add_latest FAIL
        fi

        if cx "$c" cove add beta 6.4.3 && cx "$c" grep -q "6.4.3" /root/Cove/Sites/beta.localhost/public/wp-includes/version.php; then
            res "$c" add_pinned PASS
        else
            res "$c" add_pinned FAIL
        fi

        if cx "$c" cove add gamma plain && [ "$(http_code "$c" gamma)" = "200" ]; then
            res "$c" add_plain PASS
        else
            res "$c" add_plain FAIL
        fi

        if cx "$c" cove clone alpha alpha2 && site_has "$c" alpha2 "Welcome to"; then
            res "$c" clone PASS
        else
            res "$c" clone FAIL
        fi

        if cx "$c" cove rename gamma delta && [ "$(http_code "$c" delta)" = "200" ] && ! cx "$c" test -d /root/Cove/Sites/gamma.localhost; then
            res "$c" rename PASS
        else
            res "$c" rename FAIL
        fi

        if cx "$c" bash -c 'url=$(cove login alpha 2>/dev/null | grep -oE "https://[^ \"]*cove_login_token=[A-Za-z0-9]+" | head -1); [ -n "$url" ] && curl -skL --max-time 20 -c /tmp/jar "$url" -o /dev/null && grep -q wordpress_logged_in /tmp/jar'; then
            res "$c" login PASS
        else
            res "$c" login FAIL
        fi

        if cx "$c" cove delete alpha2 && ! cx "$c" test -d /root/Cove/Sites/alpha2.localhost; then
            res "$c" delete PASS
        else
            res "$c" delete FAIL
        fi

        if cx "$c" cove status >/dev/null; then res "$c" status PASS; else res "$c" status FAIL; fi
        if cx "$c" cove health >/dev/null; then res "$c" health PASS; else res "$c" health FAIL; fi

        if cx "$c" curl -s --max-time 10 localhost:8025/api/v1/messages | grep -q "total\|messages\|\["; then
            res "$c" mailpit PASS
        else
            res "$c" mailpit FAIL
        fi

        incus restart "$c"; sleep 25
        if site_has "$c" alpha "Welcome to alpha"; then
            res "$c" reboot PASS
        else
            res "$c" reboot FAIL
        fi
    } >> "$L" 2>&1
}

lane_b() { # previous release -> candidate + post-upgrade
    local c=$1 L="$D/$c-upgrade.log"
    {
        restore "$c"
        incus file push "$SRC/install-cove.sh" "$c/root/install-cove.sh"
        # Install the PREVIOUS (latest published) release via the fixed installer
        if cx "$c" bash -c 'curl -fsSL https://github.com/anchorhost/cove/releases/latest/download/cove.sh -o /root/cove.sh' \
            && cx "$c" bash /root/install-cove.sh --dev \
            && cx "$c" cove add u1 && site_has "$c" u1 "Welcome to u1"; then
            res "$c" upgrade_prev PASS
        else
            res "$c" upgrade_prev FAIL
            res "$c" upgrade_post SKIP
            res "$c" upgrade_site SKIP
            return
        fi
        # Drop the candidate in place and run its post-upgrade hook —
        # the same sequence cove upgrade performs after downloading.
        incus file push "$SRC/cove.sh" "$c/usr/local/bin/cove"
        if cx "$c" chmod +x /usr/local/bin/cove && cx "$c" cove post-upgrade; then
            res "$c" upgrade_post PASS
        else
            res "$c" upgrade_post FAIL
        fi
        if site_has "$c" u1 "Welcome to u1"; then
            res "$c" upgrade_site PASS
        else
            res "$c" upgrade_site FAIL
        fi
    } >> "$L" 2>&1
}

lane_c() { # non-root user + sudo — the path most real Linux users hit
    local c=$1 L="$D/$c-sudo.log"
    {
        restore "$c"
        cx "$c" bash -c 'command -v sudo >/dev/null || { command -v apt-get >/dev/null && apt-get update -qq && apt-get install -y -qq sudo || dnf install -y -q sudo; }'
        cx "$c" bash -c 'id dev 2>/dev/null || useradd -m -s /bin/bash dev; echo "dev ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/dev'
        incus file push "$SRC/cove.sh" "$c/home/dev/cove.sh"
        incus file push "$SRC/install-cove.sh" "$c/home/dev/install-cove.sh"
        cx "$c" chown -R dev:dev /home/dev
        if cx "$c" su - dev -c 'bash /home/dev/install-cove.sh --dev' && cx "$c" su - dev -c 'cove version' | grep -q "Cove version"; then
            res "$c" sudo_install PASS
        else
            res "$c" sudo_install FAIL
            res "$c" sudo_add SKIP
            return
        fi
        if cx "$c" su - dev -c 'cove add usr1' && [ "$(http_code "$c" usr1)" = "200" ]; then
            res "$c" sudo_add PASS
        else
            res "$c" sudo_add FAIL
        fi
    } >> "$L" 2>&1
}

for c in $CONTAINERS; do lane_a "$c" & done
wait
for c in $UPGRADE_LANE; do lane_b "$c" & done
for c in $SUDO_LANE;    do lane_c "$c" & done
wait

# Park the fleet after a fully green run — the containers only exist for
# these tests, so hand the box's RAM/CPU back to its other workloads. Any
# failure leaves everything running so the failed container can be inspected
# (web terminal in the Incus UI, or `incus exec`).
if ! grep -q '|FAIL$' "$D/results.txt"; then
    incus stop -f $CONTAINERS
    echo "PARKED" > "$D/PARKED"
fi
touch "$D/DONE"
RUNNER_EOF

# --- Deploy + launch ---
echo "📦 Deploying candidate build + runner to $BOX..."
scp -q "$SCRIPT_DIR/cove.sh" "$SCRIPT_DIR/install-cove.sh" "$RUNNER" "$BOX:$REMOTE_DIR/"
ssh "$BOX" "mv $REMOTE_DIR/$(basename "$RUNNER") $REMOTE_DIR/matrix-runner.sh && chmod +x $REMOTE_DIR/matrix-runner.sh && rm -rf $REMOTE_DIR/matrix && (setsid nohup $REMOTE_DIR/matrix-runner.sh > $REMOTE_DIR/matrix-runner.out 2>&1 < /dev/null &) && echo '🚀 Matrix launched.'"
rm -f "$RUNNER"

if $ASYNC; then
    echo "Running in background on the box. Check progress with: ./test-matrix.sh report"
    exit 0
fi

echo "⏳ Waiting for the matrix to finish (typically 10–20 min)..."
while ! ssh "$BOX" "test -f $REMOTE_DIR/matrix/DONE" 2>/dev/null; do
    sleep 30
done
render_report
